name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Deploy Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.actor }}/deploy-pypi/deploy-pypi
          tags: latest,${{ steps.get_tag.outputs.tag }}
          password: ${{ github.token }}
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
